#!/bin/sh

curl http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz > GeoLiteCity.dat.gz
gunzip GeoLiteCity.dat.gz
mkdir data
mv GeoLiteCity.dat data/

virtualenv venv
source venv/bin/activate

pip install --upgrade -r requirements.txt

deactivate