#!/bin/sh

curl –silent –output output.txt http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz > GeoLiteCity.dat.gz
gunzip GeoLiteCity.dat.gz
mkdir data
mv GeoLiteCity.dat data/

rm output.txt
